version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "99:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/duck-maps
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
